---
- hosts: all
  sudo: True
  user: vagrant
  vars:
    data_folder: /opt/testbed
  tasks:
    - name: ensure openjdk7
      apt: name=openjdk-7-jdk state=present update_cache=yes cache_valid_time=2592000

    - name: ensure mongodb
      apt: name=mongodb state=present
    - lineinfile: dest=/etc/mongodb.conf regexp=^dbpath= line=dbpath={{ data_folder }}/mongodb

    - name: ensure tomcat
      apt: name=tomcat7 state=present

    - name: set JAVA_OPTS
      lineinfile: dest=/etc/default/tomcat7 regexp=^JAVA_OPTS= line='JAVA_OPTS="-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom -Dbdusername={{ bdusername }} -Dbdpassword={{ bdpassword }} -Ddtsusername={{ dtsusername }} -Ddtspassword={{ dtspassword }} -Xmx256m -XX:+UseConcMarkSweepGC"'

    - name: configure tomcat7 for authorized port binding
      lineinfile: dest=/etc/default/tomcat7 regexp=^AUTHBIND= line='AUTHBIND=yes'
    - lineinfile: dest=/var/lib/tomcat7/conf/server.xml regexp='<Connector port="8080"|<Connector port="80"' line='<Connector port="80" protocol="HTTP/1.1"'
    - file: dest=/etc/authbind/byport/80 owner=tomcat7 mode=0500 state=touch

    - name: stop tomcat
      service: name=tomcat7 enabled=yes state=stopped

    - name: data directories
      file: dest={{ data_folder }} owner=tomcat7 group=tomcat7 state=directory
    - file: dest={{ data_folder }}/gatling-data owner=tomcat7 group=tomcat7 state=directory
    - file: dest={{ data_folder }}/gatling-results owner=tomcat7 group=tomcat7 state=directory
    - file: dest={{ data_folder }}/gatling-bodies owner=tomcat7 group=tomcat7 state=directory
    - file: dest={{ data_folder }}/mongodb owner=mongodb group=nogroup state=directory
    - file: dest={{ data_folder }}/sample-files owner=tomcat7 group=tomcat7 state=directory

    - name: delete older ROOT dir
      file: path=/var/lib/tomcat7/webapps/ROOT state=absent
      sudo: yes
      sudo_user: tomcat7

    - name: deploy WAR
      copy: src=/home/greg/workspace/gatling-testbed/target/testbed.war dest=/var/lib/tomcat7/webapps/ROOT.war owner=tomcat7 group=tomcat7
      sudo: yes
      sudo_user: tomcat7

    - name: start tomcat
      service: name=tomcat7 enabled=yes state=started
